language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest
after_success:
  - chmod +x ./ci/send.sh
  - ./ci/send.sh success $WEBHOOK_URL
after_failure:
  - chmod +x ./ci/send.sh
  - ./ci/send.sh failure $WEBHOOK_URL