"""empty message

Revision ID: 05dbf39c5998
Revises: 38b980590aaa
Create Date: 2020-08-15 04:14:43.191567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05dbf39c5998'
down_revision = '38b980590aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'price')
    # ### end Alembic commands ###
