"""UserAccount table

Revision ID: 074cf27536b6
Revises: 
Create Date: 2020-07-21 01:29:42.476526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074cf27536b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useraccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('type', sa.Enum('customer', 'employee', 'admin', name='useraccounttype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'email')
    )
    op.create_index(op.f('ix_useraccount_email'), 'useraccount', ['email'], unique=True)
    op.create_index(op.f('ix_useraccount_username'), 'useraccount', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_useraccount_username'), table_name='useraccount')
    op.drop_index(op.f('ix_useraccount_email'), table_name='useraccount')
    op.drop_table('useraccount')
    # ### end Alembic commands ###
