"""Schema Updates

Revision ID: 1f6af2175fd3
Revises: 7315a0d2636d
Create Date: 2020-08-14 20:12:56.375371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6af2175fd3'
down_revision = '7315a0d2636d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=64), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=64), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
