"""empty message

Revision ID: 284bd739987d
Revises: e736aedded56
Create Date: 2020-08-14 19:07:10.199937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284bd739987d'
down_revision = 'e736aedded56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'quantity')
    # ### end Alembic commands ###
