"""empty message

Revision ID: 38b980590aaa
Revises: 367c27f52844
Create Date: 2020-08-15 04:13:48.407659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b980590aaa'
down_revision = '367c27f52844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'price')
    # ### end Alembic commands ###
