"""Add UNIQUE contraint to UserAccount.username and UserAccount.email

Revision ID: 41a9cb130b68
Revises: 028de4aee6fb
Create Date: 2020-07-11 12:27:46.345198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a9cb130b68'
down_revision = '028de4aee6fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_useraccount_email', table_name='useraccount')
    op.drop_index('ix_useraccount_username', table_name='useraccount')
    op.drop_table('useraccount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useraccount',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('register_date', sa.DATETIME(), nullable=False),
    sa.Column('register_confirmed', sa.BOOLEAN(), nullable=False),
    sa.Column('register_complete', sa.DATETIME(), nullable=True),
    sa.CheckConstraint("type IN ('customer', 'employee', 'admin')", name='useraccounttype'),
    sa.CheckConstraint('register_confirmed IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_useraccount_username', 'useraccount', ['username'], unique=1)
    op.create_index('ix_useraccount_email', 'useraccount', ['email'], unique=1)
    # ### end Alembic commands ###
